INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('110', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('210', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('310', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('410', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('510', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('610', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('710', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('810', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('10', '高级编译器设计与实现', '7111164296', 75, '（美）Steven S.Muchnick', '赵克佳', '机械工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('11', 'MIDP和MSA移动应用开发', '9787111250586', 48, '(美)Jonathan Knudsen', '付蓉', '机械工业出版社');
		  

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('12', '模糊测试--强制性安全漏洞发掘', '9787111257554', 59, '(美)Michael Sutton;Adam Greene;Pedram Amini', '黄陇;于莉莉;李虎', '机械工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('13', 'C++ GUI Qt 4编程(第二版)', '9787121070389', 65, '(加)Jasmin Blanchette;(英)Mark Summerfield', '闫锋欣;曾泉人;张志强', '电子工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('14', 'Web信息架构:设计大型网站(第3版)', '9787121070372', 85, 'Peter Morville;Louis Rosenfeld ', '陈建勋', '电子工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('15', '构建可扩展的Web站点', '9787121060793', 58, '(美)Cal Henderson', '徐宁', '电子工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('16', '编程卓越之道.第二卷', '9787121041259', 69, '(美)海德(Hyde,R.)', '张菲', '电子工业出版社');

INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('17', '开发自己的搜索引擎--Lucene 2.0+Heritrix', '9787115160003', 65, '邱哲;符滔滔', '', '人民邮电出版社');
		  
		  
		  
INSERT INTO BOOK(OID, NAME, ISDN, PRICE, AUTHOR, TRANSLATOR, PRESS)
          VALUES('18', '开发自己的搜索引擎--Lucene 2.0+Heritrix', '9787115160003', 65, '邱哲;符滔滔', '', '人民邮电出版社');
