CREATE TABLE ROW_BEAN
(
  STRING1 VARCHAR(64) NOT NULL,
  LONG1 DECIMAL(8),
  DICTIONARY1 VARCHAR(64 ),
  LOOKUP1 VARCHAR(64 ),
  LOOKUP2 VARCHAR(64 ),
  TITLE VARCHAR(64 ),
  FLOAT1 FLOAT,
  DOUBLE1 DECIMAL(18,2),
  INT1 INTEGER,
 PRIMARY KEY
  (
    STRING1
  )
);